### ISSUE TITLE
i have install all packages for jarvis

### ISSUE THREAD

**Issue by ShahwaizRaza** [thevickypedia/Jarvis#26] opened 2022-06-19 14:10 UTC
but it shows an error every time No module named 'executors.commander' or executors.geolocator or import geo_locator

**Comment by thevickypedia** [comment] 2022-06-20 07:33
Thanks for reporting. From the description it sounds like your current working directory has an issue since `executors` dir is a part of the main module.
Can you please provide minimum reproducible code or screenshots for me to begin with?
Please refer to [reporting guidelines](https://github.com/thevickypedia/Jarvis/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) on the information to include when you raise a bug report.

**Comment by thevickypedia** [comment] 2022-06-27 13:59
Can you please check the current working directory of your project. A `pwd` in working terminal or `import os; print(os.getcwd())` should get it.
Since both `modules` and `executors` are directories within the main module, there shouldn't be a start up issue unless the current working directory is incorrect.

To answer to your second screnshot, `internet.py` cannot be run separately so that is expected. Only `jarvis.py` can be triggered from the root dir which should import all the required modules and startup.

**Comment by ShahwaizRaza** [comment] 2022-07-06 13:17
i got an error, no module name 'vpn'
which package are you using?

**Comment by thevickypedia** [comment] 2022-07-06 15:16
Can you check if the command works in your terminal, I barely use windows OS and it was working in my machine after I installed `git`
Let me know if that doesn't fix, I'll release a bug fix with exception handlers around it since it is an un-important task.

**Comment by thevickypedia** [comment] 2022-07-06 15:17
Thanks for bringing this up, I just realized I'm checking for `git` installation in `MacOS` but not `Windows`
I'll release a fix for that as well

**Comment by ShahwaizRaza** [comment] 2022-07-06 15:26
git already installed in windows.

**Comment by thevickypedia** [comment] 2022-07-06 15:32
The problem you stated shouldn't rely on git installation in the first place, can you try the command `netsh wlan show interfaces` in your cmd and see if it works.

**Comment by ShahwaizRaza** [comment] 2022-07-06 15:35
wait, I am using pc not a laptop.
![image](https://user-images.githubusercontent.com/88272647/177588792-96cebcdc-ab20-41a8-96ad-7435a123e840.png)

**Comment by ShahwaizRaza** [comment] 2022-07-06 15:37
i add try & except.
![image](https://user-images.githubusercontent.com/88272647/177588944-c34888c9-ecf8-4bb3-b1bb-39478feaa2af.png)
-------------------------------------------------------
then it shows this in terminal
![image](https://user-images.githubusercontent.com/88272647/177589071-d3e03173-cd65-4dd2-81b0-7d8aca50ac0a.png)

**Comment by thevickypedia** [comment] 2022-07-06 15:43
Good to know, the command is to check wireless interfaces and I have never tried running on a wired PC
I'll add that to my list of fixes in the next release. About the warning message, you may ignore it. It runs only on Mac with a cron schedule if you have robinhood credentials stored as env vars but imports the module regardless.
You shouldn't have received the warning in the first place since both your CWD and Parent are the same. It might be because of spaces or backslashes. I implement a fix for that as well.

**Comment by ShahwaizRaza** [comment] 2022-07-06 15:49
my current and parent directory are not the same.

**Comment by thevickypedia** [comment] 2022-07-06 18:48
Of course it will not be the same when you run that piece of code by itself. Current is current and parent is the directory where the current dir is present. I was talking about your previous [screenshot](https://user-images.githubusercontent.com/88272647/177589071-d3e03173-cd65-4dd2-81b0-7d8aca50ac0a.png) when you spun up Jarvis to `Sentry Mode`
That's because it does a string match instead of a path match using `os.path.normpath()` or `os.path.realpath()` or `os.path.abspath()`

**Comment by thevickypedia** [comment] 2022-07-07 04:00
Issue has been addressed in 93b57ccb21ec63e4c5f2a8108d5210a79f9244ae

**Closed by thevickypedia** 2022-07-07 04:00 UTC
Labels: bug
